project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "YOUR PROJECT TITLE"
  author:
    - Harmeet Singh Bagga (hb2783)
    - Liangtai Xing (lx2318)
  repo-url: https://github.com/harmith-singh/RecommenderSystem.git
  date: 30-Nov-2023
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


